version: '3.7'
services:

  cassandra:
    image: cassandra:3.11.4
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
    restart: always
    volumes:
      - /var/lib/cassandra